# get all orders
GET http://localhost:3000/orders

###

# create a new order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "user": "647e274b961b8485a84dbdc6",
  "products": [
    {
      "product": "647e24aa961b8485a84dbdbb",
      "quantity": 1,
      "size": "5.0"
    },
    {
      "product": "647e271a961b8485a84dbdc4",
      "quantity": 1,
      "size": "XL"
    }
  ],
  "shippingAddress": "123 Main St, Tel Aviv, Israel",
  "paymentMethod": "Credit Card"
}


###

# get order by id
GET http://localhost:3000/orders/649413868a4ed1705a9b4895

###

# update order
PATCH http://localhost:3000/orders
Content-Type: application/json

{
  "product": {
    "_id": "6493345dfc9bba4d96521f17",
    "name": "SurfBoardTest2"
  }
}

###

# filter orders
POST http://localhost:3000/orders/filter
Content-Type: application/json

{
  "product": {
    "category": "Surfing",
    "name": "Wetsuit"
  }
}

###

# delete product
DELETE http://localhost:3000/orders
Content-Type: application/json

{
  "_id": "6493f42af8c23d1abc6355bf"
}






