GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
  "product": {
    "name": "SurfBoardTest2"
  }
}

###

GET http://localhost:3000/products/6493345dfc9bba4d96521f17

###

PATCH http://localhost:3000/products
Content-Type: application/json

{
  "product": {
    "_id": "6493345dfc9bba4d96521f17",
    "name": "SurfBoardTest2"
  }
}

###

POST http://localhost:3000/products/filter
Content-Type: application/json

{
  "product": {
    "category": "Surfing",
    "name": "Wetsuit"
  }
}


###

DELETE http://localhost:3000/products
Content-Type: application/json

{
  "_id": "6493345dfc9bba4d96521f17"
}

###




