# get all products
GET http://localhost:3000/products

###

# create a new product
POST http://localhost:3000/products
Content-Type: application/json

 {"product":{
     "name": "SurfBoardTest2",
         "price": 59.9,
         "frontImage": "https://picsum.photos/200",
         "category": "Category",
         "brand": "Lion",
         "details": [
         {
             "size": "XL",
             "quantityInStock": 10
         }
     ]
 }
 }

###

# get product by id
GET http://localhost:3000/products/649415d249554cbf3cf96c4b

###

# update product
PATCH http://localhost:3000/products
Content-Type: application/json

{

  "product": {
    "_id": "649415d249554cbf3cf96c4b",
    "name": "SurfBoardTest2Update"
}
}

###

# filter products
POST http://localhost:3000/products/filter
Content-Type: application/json

{
  "product": {
    "name": "SurfBoardTest2Update"
  }
}

###

# delete product
DELETE http://localhost:3000/products
Content-Type: application/json

{
  "_id": "649415d249554cbf3cf96c4b"
}






